[package]
name = "example-rust-project"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
axum = "0.7"

[dev-dependencies]
tokio-test = "0.4" 