source 'https://rubygems.org'

gem 'rails', '~> 7.0.0'
gem 'pg', '>= 1.1'
gem 'puma', '~> 5.0'
gem 'devise', '4.9.2'

group :development, :test do
  gem 'rspec-rails', '~> 6.0.0'
  gem 'factory_bot_rails', '~> 6.2.0'
end