name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install xvfb
      run: sudo apt-get install -y xvfb
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: |
        npm run lint
        echo "## Lint Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ Lint completed successfully" >> $GITHUB_STEP_SUMMARY
    
    - name: Run tests
      run: |
        xvfb-run -a npm run test
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ All tests passed" >> $GITHUB_STEP_SUMMARY 